CREATE TABLE CURSO
(
    ID VARCHAR(36) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CARGA_HORARIA VARCHAR(10) NOT NULL,
    DATA_INICIO VARCHAR(10) NOT NULL,
    DISCIPLINA VARCHAR(50) NOT NULL,

    PRIMARY KEY(ID),
);






